### ISSUE TITLE
US 01.01.01 (adding ingredients)

### ISSUE THREAD

**Issue by a-s-ahmed** [CMPUT301F22T01/FoodBit#2]

**Comment by hr-jackson** [comment]
Location options, category options, rounding?

Expected Behaviour:
- an ingredient can be added with the use of the add button
- when button is pressed a screen will pop up asking the user to input the details of the ingredient being added, including the description, best before date, location, amount, unit, and ingredient category
- the cancel button can be pressed on the pop up to cancel the addition of the new ingredient
- finalization of the addition is done by pressing the add button on the pop up which will then add the new ingredient to the list
